# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "241c687916ef7872cf252130bbe2d80a"
name = "docverify"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_metaobjects,read_orders,read_products,write_files,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
