api_version = "2025-07"

[[extensions]]

uid = "34aa0729-7a1c-cec1-b125-fbb36ce55734a495d0bf"

type = "ui_extension"
name = "Doc Upload Block"
handle = "doc-upload-block"

  [[extensions.targeting]]
  module = "./src/Checkout.jsx"
  target = "purchase.checkout.block.render"

[extensions.settings]
  [[extensions.settings.fields]]
  key = "upload_title"
  type = "single_line_text_field"
  name = "Upload prompt title"

  [[extensions.settings.fields]]
  key = "helper_text"
  type = "single_line_text_field"
  name = "Helper text"

  [[extensions.settings.fields]]
  key = "error_message"
  type = "single_line_text_field"
  name = "Error message"

  [[extensions.settings.fields]]
  key = "button_label"
  type = "single_line_text_field"
  name = "Button label"